services:
  flask:
    image: python:3.9
    container_name: rathole-api
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./etc:/etc/rathole
      - ./app:/app
    working_dir: /app
    # command: bash -c "pip install -r requirements.txt && gunicorn -w 4 -b 0.0.0.0:5000 app:app"
    command: bash -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    networks:
      ctfd:
networks:
  ctfd: